name: musix_final
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^0.5.0
  cupertino_icons: ^1.0.0
  dartz: ^0.9.2
  dio: ^3.0.10
  get: 3.15.0
  get_storage: ^1.3.2
  styled_widget: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.3.0

flutter:
  uses-material-design: true
